### ISSUE TITLE
binary install does not exist

### ISSUE THREAD

**Issue by georgettica** [alvinvaja/spell-correction#1]
I tried to go to the link in the README but it was broken

running this was also problematic aas it required `PyQt5` which was not able to install on my machine

let me know if this is something you wish to maintain or not

**Comment by alvinvaja** [comment]
hi, sorry, will remove the broken link, it was directed to drive link which email was terminated long ago

and yes it required older version of `PyQt` and I won't be rewriting this in newer version of `PyQt` anytime soon, sorry!
